[package]
name = "eushully"
version = "0.1.0"
authors = ["Douman <douman@gmx.se>"]

[dependencies]
winapi = "*"
windows-win = "^0.3.0"
lazy-bytes-cast = "^0.1.0"

[[bin]]
path = "src/nocd.rs"
name = "eushully_nocd"
