[package]
name = "clipboard_monitor"
version = "1.0.0"
authors = ["DoumanAsh <custparasite@gmx.se>"]

[dependencies]
clipboard-win = "*"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
