[package]
name = "hash_sum"
version = "1.0.0"
authors = ["DoumanAsh <custparasite@gmx.se>"]

[dependencies]
rust-crypto = "*"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
